// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHKeEw_nxzIG6DmN1DcpLtT7RelcwuOE8',
    appId: '1:935089359551:web:875d5eeec293af929ad40a',
    messagingSenderId: '935089359551',
    projectId: 'flutter-firebase-lab-e30eb',
    authDomain: 'flutter-firebase-lab-e30eb.firebaseapp.com',
    storageBucket: 'flutter-firebase-lab-e30eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAebe761t8v19kDF5IRTuBqj5DMeerX_fg',
    appId: '1:935089359551:android:611ba0713f3a2cbd9ad40a',
    messagingSenderId: '935089359551',
    projectId: 'flutter-firebase-lab-e30eb',
    storageBucket: 'flutter-firebase-lab-e30eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Leye4Om2Px6XImlzFjDpNZlBk2AUf00',
    appId: '1:935089359551:ios:b01133458c5e23539ad40a',
    messagingSenderId: '935089359551',
    projectId: 'flutter-firebase-lab-e30eb',
    storageBucket: 'flutter-firebase-lab-e30eb.appspot.com',
    iosClientId: '935089359551-c6argcfg4uek5qc6n1jt421jc5dgt0tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gisLogOut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Leye4Om2Px6XImlzFjDpNZlBk2AUf00',
    appId: '1:935089359551:ios:b01133458c5e23539ad40a',
    messagingSenderId: '935089359551',
    projectId: 'flutter-firebase-lab-e30eb',
    storageBucket: 'flutter-firebase-lab-e30eb.appspot.com',
    iosClientId: '935089359551-c6argcfg4uek5qc6n1jt421jc5dgt0tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gisLogOut',
  );
}
